language: node_js

before_script:
  - npm install nightwatch http-server
  - ./node_modules/http-server/bin/http-server . &
script:
  - ./node_modules/nightwatch/bin/nightwatch -c nightwatch.js --env firefox
  - pkill node
